# Generated by Django 5.0.3 on 2024-03-08 00:34

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Admin')
    Group.objects.get_or_create(name='Accountant')
    Group.objects.get_or_create(name='Salesperson')

class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(create_groups),
    ]

