# Generated by Django 5.0.3 on 2024-03-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store_app", "0002_create_groups_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(default="", max_length=13),
            preserve_default=False,
        ),
    ]
